[project]
name = "code-mentor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "asyncio>=4.0.0",
    "fastapi[all]>=0.121.3",
    "ruff>=0.14.6",
    "tree-sitter>=0.25.2",
    "tree-sitter-python>=0.25.0",
]
